### ISSUE TITLE
Lean Markdown

### ISSUE THREAD

**Issue by ghost** [libre-hackerman/metromono#1]
Necesitas más información en el README.Como mínimo cómo usar el programa, sus salidas(errores y cómo solucionarlos, si los hubiera), y lo fundamental, proporcionar información sobre cómo suplir las dependencias del programa.

**Comment by libre-hackerman** [comment]
Proporciono información sobre qué dependencias necesita, en particular pysine que es más rara de encontrar. Aparte de eso es un metrónomo. No tiene mucha historia su uso. Gracias por la sugerencia en cualquier caso.
